apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ownpulse-userdocs.fullname" . }}
  labels:
    {{- include "ownpulse-userdocs.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "ownpulse-userdocs.selectorLabels" . | nindent 6 }}
