replicaCount: 1

image:
  repository: ghcr.io/ownpulse/ownpulse-userdocs
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: docs.ownpulse.health
  tls:
    enabled: true
    secretName: ownpulse-userdocs-tls

resources:
  requests:
    memory: "16Mi"
    cpu: "10m"
  limits:
    memory: "64Mi"
    cpu: "100m"
