// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) OwnPulse Contributors

//! Curated SNP annotation seed data from public databases (ClinVar, PharmGKB, SNPedia, GWAS Catalog).
//!
//! This module provides well-known, clinically significant SNP annotations for
//! genetic interpretation. The data is sourced from public genomic databases
//! and is NOT user data — it is shared reference information.

use sqlx::PgPool;
use tracing::info;

struct Annotation {
    rsid: &'static str,
    gene: Option<&'static str>,
    category: &'static str,
    title: &'static str,
    summary: &'static str,
    risk_allele: Option<&'static str>,
    normal_allele: Option<&'static str>,
    significance: &'static str,
    evidence_level: &'static str,
    source: &'static str,
    source_id: Option<&'static str>,
    population_frequency: Option<f64>,
}

/// Seed the `snp_annotations` table with curated annotation data.
///
/// Uses ON CONFLICT DO UPDATE so the function is idempotent — safe to call
/// on every startup or as part of migration seeding.
pub async fn seed_annotations(pool: &PgPool) -> Result<(), sqlx::Error> {
    let annotations = all_annotations();
    let count = annotations.len();

    for ann in &annotations {
        sqlx::query(
            "INSERT INTO snp_annotations (rsid, gene, category, title, summary, risk_allele,
                normal_allele, significance, evidence_level, source, source_id,
                population_frequency)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
             ON CONFLICT (rsid, source) DO UPDATE SET
                gene = EXCLUDED.gene,
                category = EXCLUDED.category,
                title = EXCLUDED.title,
                summary = EXCLUDED.summary,
                risk_allele = EXCLUDED.risk_allele,
                normal_allele = EXCLUDED.normal_allele,
                significance = EXCLUDED.significance,
                evidence_level = EXCLUDED.evidence_level,
                source_id = EXCLUDED.source_id,
                population_frequency = EXCLUDED.population_frequency",
        )
        .bind(ann.rsid)
        .bind(ann.gene)
        .bind(ann.category)
        .bind(ann.title)
        .bind(ann.summary)
        .bind(ann.risk_allele)
        .bind(ann.normal_allele)
        .bind(ann.significance)
        .bind(ann.evidence_level)
        .bind(ann.source)
        .bind(ann.source_id)
        .bind(ann.population_frequency)
        .execute(pool)
        .await?;
    }

    info!(count, "seeded snp_annotations");
    Ok(())
}

fn all_annotations() -> Vec<Annotation> {
    vec![
        // ========================================================================
        // Health Risk variants
        // ========================================================================
        Annotation {
            rsid: "rs1801133",
            gene: Some("MTHFR"),
            category: "health_risk",
            title: "MTHFR C677T Variant",
            summary: "Associated with reduced folate metabolism. Homozygous carriers have ~30% of normal MTHFR enzyme activity.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("3520"),
            population_frequency: Some(0.34),
        },
        Annotation {
            rsid: "rs1801131",
            gene: Some("MTHFR"),
            category: "health_risk",
            title: "MTHFR A1298C Variant",
            summary: "Associated with mildly reduced MTHFR enzyme activity. Less impactful than C677T alone.",
            risk_allele: Some("C"),
            normal_allele: Some("AA"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "clinvar",
            source_id: Some("3521"),
            population_frequency: Some(0.30),
        },
        Annotation {
            rsid: "rs4680",
            gene: Some("COMT"),
            category: "health_risk",
            title: "COMT Val158Met",
            summary: "Affects dopamine and estrogen metabolism. The Met variant (A allele) results in slower COMT enzyme activity.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("4680"),
            population_frequency: Some(0.49),
        },
        Annotation {
            rsid: "rs1799945",
            gene: Some("HFE"),
            category: "health_risk",
            title: "HFE H63D Variant",
            summary: "Associated with increased iron absorption. Homozygous carriers have mildly elevated hereditary hemochromatosis risk.",
            risk_allele: Some("G"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("5320"),
            population_frequency: Some(0.14),
        },
        Annotation {
            rsid: "rs1800562",
            gene: Some("HFE"),
            category: "health_risk",
            title: "HFE C282Y Variant",
            summary: "Primary variant for hereditary hemochromatosis. Homozygous carriers have significantly increased iron absorption.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("5321"),
            population_frequency: Some(0.06),
        },
        Annotation {
            rsid: "rs429358",
            gene: Some("APOE"),
            category: "health_risk",
            title: "APOE e4 Variant (rs429358)",
            summary: "One of two SNPs defining APOE isoforms. The C allele contributes to the e4 allele, associated with increased Alzheimer's disease risk.",
            risk_allele: Some("C"),
            normal_allele: Some("TT"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("7929"),
            population_frequency: Some(0.16),
        },
        Annotation {
            rsid: "rs7412",
            gene: Some("APOE"),
            category: "health_risk",
            title: "APOE e2 Variant (rs7412)",
            summary: "One of two SNPs defining APOE isoforms. The T allele contributes to the protective e2 allele.",
            risk_allele: Some("C"),
            normal_allele: Some("TT"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("7930"),
            population_frequency: Some(0.08),
        },
        Annotation {
            rsid: "rs334",
            gene: Some("HBB"),
            category: "health_risk",
            title: "Sickle Cell Trait (HbS)",
            summary: "The sickle cell variant in the beta-globin gene. Heterozygous carriers have sickle cell trait; homozygous have sickle cell disease.",
            risk_allele: Some("T"),
            normal_allele: Some("AA"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("15126"),
            population_frequency: Some(0.05),
        },
        Annotation {
            rsid: "rs1800497",
            gene: Some("ANKK1"),
            category: "health_risk",
            title: "DRD2/ANKK1 Taq1A",
            summary: "Associated with altered dopamine receptor density. The A1 allele (T) is linked to reduced D2 receptor availability.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.21),
        },
        Annotation {
            rsid: "rs53576",
            gene: Some("OXTR"),
            category: "health_risk",
            title: "Oxytocin Receptor Variant",
            summary: "Associated with social behavior and empathy. The G allele is linked to higher empathy scores and social sensitivity.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.39),
        },
        Annotation {
            rsid: "rs6265",
            gene: Some("BDNF"),
            category: "health_risk",
            title: "BDNF Val66Met",
            summary: "Affects brain-derived neurotrophic factor secretion. The Met variant (T allele) is associated with reduced activity-dependent BDNF release.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("6265"),
            population_frequency: Some(0.20),
        },
        Annotation {
            rsid: "rs1815739",
            gene: Some("ACTN3"),
            category: "health_risk",
            title: "ACTN3 R577X (Sprint Gene)",
            summary: "Determines muscle fiber type composition. The T allele (577X) results in alpha-actinin-3 deficiency, favoring endurance over sprint performance.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.42),
        },
        Annotation {
            rsid: "rs4988235",
            gene: Some("LCT"),
            category: "health_risk",
            title: "Lactose Tolerance",
            summary: "Regulates lactase persistence into adulthood. The T allele allows continued lactose digestion; CC genotype indicates likely lactose intolerance.",
            risk_allele: Some("C"),
            normal_allele: Some("TT"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.50),
        },
        Annotation {
            rsid: "rs762551",
            gene: Some("CYP1A2"),
            category: "health_risk",
            title: "Caffeine Metabolism Speed",
            summary: "Determines caffeine metabolism rate. The A allele is associated with fast caffeine metabolism; C allele with slow metabolism.",
            risk_allele: Some("C"),
            normal_allele: Some("AA"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("762551"),
            population_frequency: Some(0.37),
        },
        Annotation {
            rsid: "rs1229984",
            gene: Some("ADH1B"),
            category: "health_risk",
            title: "Alcohol Metabolism (ADH1B)",
            summary: "Affects alcohol dehydrogenase activity. The T allele results in faster ethanol oxidation, associated with reduced alcohol dependence risk.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "protective",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("18390"),
            population_frequency: Some(0.28),
        },
        Annotation {
            rsid: "rs671",
            gene: Some("ALDH2"),
            category: "health_risk",
            title: "Alcohol Flush Reaction (ALDH2)",
            summary: "Determines acetaldehyde metabolism. The A allele causes ALDH2 deficiency, leading to facial flushing and nausea after alcohol consumption.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("18391"),
            population_frequency: Some(0.17),
        },
        Annotation {
            rsid: "rs12979860",
            gene: Some("IFNL4"),
            category: "health_risk",
            title: "Hepatitis C Treatment Response",
            summary: "Predicts response to interferon-based hepatitis C treatment. CC genotype associated with higher spontaneous clearance and treatment response.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.37),
        },
        Annotation {
            rsid: "rs1800795",
            gene: Some("IL6"),
            category: "health_risk",
            title: "IL-6 Promoter Variant",
            summary: "Affects interleukin-6 expression levels. The C allele is associated with higher IL-6 levels and increased inflammatory response.",
            risk_allele: Some("C"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.42),
        },
        Annotation {
            rsid: "rs1800629",
            gene: Some("TNF"),
            category: "health_risk",
            title: "TNF-alpha Promoter Variant",
            summary: "Affects tumor necrosis factor alpha expression. The A allele is associated with higher TNF-alpha levels and increased inflammatory risk.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "clinvar",
            source_id: Some("1800629"),
            population_frequency: Some(0.14),
        },
        Annotation {
            rsid: "rs7903146",
            gene: Some("TCF7L2"),
            category: "health_risk",
            title: "Type 2 Diabetes Risk (TCF7L2)",
            summary: "Strongest common genetic risk factor for type 2 diabetes. The T allele increases risk by affecting insulin secretion.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.30),
        },
        Annotation {
            rsid: "rs9939609",
            gene: Some("FTO"),
            category: "health_risk",
            title: "FTO Obesity Risk Variant",
            summary: "Associated with increased BMI and obesity risk. The A allele affects appetite regulation and energy expenditure.",
            risk_allele: Some("A"),
            normal_allele: Some("TT"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.42),
        },
        Annotation {
            rsid: "rs1800566",
            gene: Some("NQO1"),
            category: "health_risk",
            title: "NQO1 Pro187Ser",
            summary: "Affects quinone oxidoreductase activity. The T allele results in reduced NQO1 enzyme activity, affecting detoxification capacity.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "clinvar",
            source_id: Some("1800566"),
            population_frequency: Some(0.22),
        },
        Annotation {
            rsid: "rs1805007",
            gene: Some("MC1R"),
            category: "health_risk",
            title: "MC1R Red Hair Variant (R151C)",
            summary: "Associated with red hair, fair skin, and increased melanoma risk. One of several MC1R variants affecting pigmentation.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("1805007"),
            population_frequency: Some(0.08),
        },
        Annotation {
            rsid: "rs4149056",
            gene: Some("SLCO1B1"),
            category: "health_risk",
            title: "SLCO1B1 Statin Myopathy Risk",
            summary: "Affects statin transport into liver cells. The C allele increases risk of statin-induced myopathy, particularly with simvastatin.",
            risk_allele: Some("C"),
            normal_allele: Some("TT"),
            significance: "risk_factor",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166154579"),
            population_frequency: Some(0.15),
        },
        Annotation {
            rsid: "rs1800544",
            gene: Some("ADRA2A"),
            category: "health_risk",
            title: "ADRA2A Alpha-2A Adrenergic Receptor",
            summary: "Affects norepinephrine signaling. Associated with stress response, attention, and metabolic regulation.",
            risk_allele: Some("C"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "moderate",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.26),
        },
        Annotation {
            rsid: "rs4633",
            gene: Some("COMT"),
            category: "health_risk",
            title: "COMT H62H Variant",
            summary: "A synonymous variant in the COMT gene often inherited with Val158Met. May contribute to altered catecholamine metabolism through linkage.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "risk_factor",
            evidence_level: "limited",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.46),
        },
        Annotation {
            rsid: "rs4411417",
            gene: Some("GAD1"),
            category: "health_risk",
            title: "GAD1 GABA Synthesis Variant",
            summary: "Affects glutamate decarboxylase expression. Associated with GABA levels and anxiety-related traits.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "risk_factor",
            evidence_level: "limited",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.33),
        },
        Annotation {
            rsid: "rs4680",
            gene: Some("COMT"),
            category: "pharmacogenomics",
            title: "COMT Val158Met (Drug Metabolism)",
            summary: "Affects catechol-O-methyltransferase activity. Relevant for metabolism of catecholamine-based drugs and pain sensitivity.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104810"),
            population_frequency: Some(0.49),
        },
        // ========================================================================
        // Pharmacogenomics variants
        // ========================================================================
        Annotation {
            rsid: "rs1065852",
            gene: Some("CYP2D6"),
            category: "pharmacogenomics",
            title: "CYP2D6*10 Variant",
            summary: "Reduced CYP2D6 enzyme activity. Affects metabolism of codeine, SSRIs, tamoxifen, and many other drugs.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104852"),
            population_frequency: Some(0.25),
        },
        Annotation {
            rsid: "rs3892097",
            gene: Some("CYP2D6"),
            category: "pharmacogenomics",
            title: "CYP2D6*4 (Poor Metabolizer)",
            summary: "Non-functional CYP2D6 allele. Homozygous carriers are poor metabolizers of many drugs including codeine, tramadol, and tamoxifen.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104853"),
            population_frequency: Some(0.20),
        },
        Annotation {
            rsid: "rs4244285",
            gene: Some("CYP2C19"),
            category: "pharmacogenomics",
            title: "CYP2C19*2 (Poor Metabolizer)",
            summary: "Non-functional CYP2C19 allele. Affects clopidogrel activation, proton pump inhibitor metabolism, and some antidepressants.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104849"),
            population_frequency: Some(0.15),
        },
        Annotation {
            rsid: "rs12248560",
            gene: Some("CYP2C19"),
            category: "pharmacogenomics",
            title: "CYP2C19*17 (Rapid Metabolizer)",
            summary: "Increased CYP2C19 enzyme activity. Rapid metabolizers may need higher doses of some drugs or experience reduced efficacy.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104850"),
            population_frequency: Some(0.21),
        },
        Annotation {
            rsid: "rs1799853",
            gene: Some("CYP2C9"),
            category: "pharmacogenomics",
            title: "CYP2C9*2 (Warfarin Sensitivity)",
            summary: "Reduced CYP2C9 enzyme activity. Carriers require lower warfarin doses to achieve therapeutic anticoagulation.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104846"),
            population_frequency: Some(0.12),
        },
        Annotation {
            rsid: "rs1057910",
            gene: Some("CYP2C9"),
            category: "pharmacogenomics",
            title: "CYP2C9*3 (Warfarin Sensitivity)",
            summary: "Significantly reduced CYP2C9 enzyme activity. Carriers need substantially lower warfarin doses.",
            risk_allele: Some("C"),
            normal_allele: Some("AA"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104847"),
            population_frequency: Some(0.06),
        },
        Annotation {
            rsid: "rs9923231",
            gene: Some("VKORC1"),
            category: "pharmacogenomics",
            title: "VKORC1 Warfarin Dosing (-1639G>A)",
            summary: "Major determinant of warfarin dose requirement. The A allele reduces VKORC1 expression, requiring lower warfarin doses.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166104848"),
            population_frequency: Some(0.39),
        },
        Annotation {
            rsid: "rs9934438",
            gene: Some("VKORC1"),
            category: "pharmacogenomics",
            title: "VKORC1 1173C>T Warfarin Dosing",
            summary: "In strong linkage disequilibrium with rs9923231. The T allele is associated with lower warfarin dose requirements.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166154580"),
            population_frequency: Some(0.40),
        },
        Annotation {
            rsid: "rs28399504",
            gene: Some("CYP3A4"),
            category: "pharmacogenomics",
            title: "CYP3A4*2 Variant",
            summary: "Reduced CYP3A4 enzyme activity. Affects metabolism of many drugs including statins, calcium channel blockers, and immunosuppressants.",
            risk_allele: Some("G"),
            normal_allele: Some("AA"),
            significance: "drug_response",
            evidence_level: "moderate",
            source: "pharmgkb",
            source_id: Some("PA166104851"),
            population_frequency: Some(0.03),
        },
        Annotation {
            rsid: "rs2032582",
            gene: Some("ABCB1"),
            category: "pharmacogenomics",
            title: "ABCB1 2677G>T/A (P-glycoprotein)",
            summary: "Affects drug efflux pump activity. Influences absorption and brain penetration of many drugs.",
            risk_allele: Some("T"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "moderate",
            source: "pharmgkb",
            source_id: Some("PA166154581"),
            population_frequency: Some(0.43),
        },
        Annotation {
            rsid: "rs1045642",
            gene: Some("ABCB1"),
            category: "pharmacogenomics",
            title: "ABCB1 3435C>T (P-glycoprotein)",
            summary: "Affects P-glycoprotein expression and drug transport. The T allele is associated with reduced intestinal P-gp expression.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "drug_response",
            evidence_level: "moderate",
            source: "pharmgkb",
            source_id: Some("PA166154582"),
            population_frequency: Some(0.48),
        },
        Annotation {
            rsid: "rs4148323",
            gene: Some("UGT1A1"),
            category: "pharmacogenomics",
            title: "UGT1A1*6 (Gilbert's Syndrome / Irinotecan)",
            summary: "Reduced UGT1A1 enzyme activity. Associated with Gilbert's syndrome and increased toxicity risk from irinotecan.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166154583"),
            population_frequency: Some(0.09),
        },
        Annotation {
            rsid: "rs1799971",
            gene: Some("OPRM1"),
            category: "pharmacogenomics",
            title: "OPRM1 A118G (Opioid Receptor)",
            summary: "Affects mu-opioid receptor function. The G allele is associated with reduced opioid analgesic efficacy and altered addiction risk.",
            risk_allele: Some("G"),
            normal_allele: Some("AA"),
            significance: "drug_response",
            evidence_level: "moderate",
            source: "pharmgkb",
            source_id: Some("PA166154584"),
            population_frequency: Some(0.15),
        },
        Annotation {
            rsid: "rs1128503",
            gene: Some("ABCB1"),
            category: "pharmacogenomics",
            title: "ABCB1 1236C>T (P-glycoprotein)",
            summary: "Synonymous variant affecting P-glycoprotein mRNA stability. Part of the common ABCB1 haplotype affecting drug transport.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "drug_response",
            evidence_level: "limited",
            source: "pharmgkb",
            source_id: Some("PA166154585"),
            population_frequency: Some(0.42),
        },
        Annotation {
            rsid: "rs2279343",
            gene: Some("CYP2B6"),
            category: "pharmacogenomics",
            title: "CYP2B6*4 Variant",
            summary: "Altered CYP2B6 enzyme activity. Affects metabolism of efavirenz, cyclophosphamide, and bupropion.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "moderate",
            source: "pharmgkb",
            source_id: Some("PA166154586"),
            population_frequency: Some(0.31),
        },
        Annotation {
            rsid: "rs3745274",
            gene: Some("CYP2B6"),
            category: "pharmacogenomics",
            title: "CYP2B6*6 (516G>T)",
            summary: "Reduced CYP2B6 enzyme activity. Most common variant affecting efavirenz, methadone, and bupropion metabolism.",
            risk_allele: Some("T"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166154587"),
            population_frequency: Some(0.26),
        },
        Annotation {
            rsid: "rs4986893",
            gene: Some("CYP2C19"),
            category: "pharmacogenomics",
            title: "CYP2C19*3 (Poor Metabolizer)",
            summary: "Non-functional CYP2C19 allele, common in East Asian populations. Affects clopidogrel and other drug metabolism.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "drug_response",
            evidence_level: "strong",
            source: "pharmgkb",
            source_id: Some("PA166154588"),
            population_frequency: Some(0.03),
        },
        // ========================================================================
        // Trait variants
        // ========================================================================
        Annotation {
            rsid: "rs12913832",
            gene: Some("HERC2"),
            category: "trait",
            title: "Eye Color (Blue/Brown)",
            summary: "Primary determinant of blue vs. brown eye color. The A allele is strongly associated with blue eyes; GG with brown eyes.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.38),
        },
        Annotation {
            rsid: "rs1426654",
            gene: Some("SLC24A5"),
            category: "trait",
            title: "Skin Pigmentation",
            summary: "Major determinant of skin pigmentation. The A allele is associated with lighter skin and is nearly fixed in European populations.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.45),
        },
        Annotation {
            rsid: "rs4481887",
            gene: None,
            category: "trait",
            title: "Asparagus Anosmia",
            summary: "Affects ability to detect the odor of asparagus metabolites in urine. The A allele is associated with inability to smell asparagus metabolites.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "benign",
            evidence_level: "moderate",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.45),
        },
        Annotation {
            rsid: "rs1800955",
            gene: Some("DRD4"),
            category: "trait",
            title: "DRD4 Novelty Seeking",
            summary: "Affects dopamine D4 receptor expression. The C allele is associated with higher novelty-seeking behavior in some studies.",
            risk_allele: Some("C"),
            normal_allele: Some("TT"),
            significance: "benign",
            evidence_level: "limited",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.40),
        },
        Annotation {
            rsid: "rs4950",
            gene: None,
            category: "trait",
            title: "Leadership Tendency",
            summary: "Associated with leadership role occupancy in GWAS studies. Effect size is very small and environment plays a much larger role.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "benign",
            evidence_level: "preliminary",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.41),
        },
        Annotation {
            rsid: "rs7495174",
            gene: Some("OCA2"),
            category: "trait",
            title: "OCA2 Eye Color Modifier",
            summary: "Contributes to eye color variation. Works in concert with HERC2 rs12913832 to determine iris pigmentation.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.36),
        },
        Annotation {
            rsid: "rs17822931",
            gene: Some("ABCC11"),
            category: "trait",
            title: "Earwax Type (Wet/Dry)",
            summary: "Determines earwax consistency. The T allele produces dry earwax (common in East Asian populations); CC produces wet earwax.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.30),
        },
        Annotation {
            rsid: "rs72921001",
            gene: Some("OR6A2"),
            category: "trait",
            title: "Cilantro/Coriander Taste Perception",
            summary: "Affects perception of cilantro flavor. The A allele is associated with detecting a soapy taste in cilantro.",
            risk_allele: Some("A"),
            normal_allele: Some("CC"),
            significance: "benign",
            evidence_level: "moderate",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.15),
        },
        Annotation {
            rsid: "rs1800401",
            gene: Some("OCA2"),
            category: "trait",
            title: "OCA2 R419Q (Blue Eyes)",
            summary: "Contributes to lighter eye color. The T allele reduces OCA2 protein activity, contributing to blue/green eye color.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "moderate",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.07),
        },
        Annotation {
            rsid: "rs4680",
            gene: Some("COMT"),
            category: "trait",
            title: "COMT Warrior/Worrier Trait",
            summary: "The Val (G) allele is associated with better stress resilience (Warrior); Met (A) with better cognitive performance under low stress (Worrier).",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "moderate",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.49),
        },
        Annotation {
            rsid: "rs4988235",
            gene: Some("LCT"),
            category: "trait",
            title: "Lactase Persistence (Trait)",
            summary: "Determines whether you maintain the ability to digest lactose into adulthood. TT/CT = lactase persistent; CC = likely lactose intolerant.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.50),
        },
        Annotation {
            rsid: "rs1805009",
            gene: Some("MC1R"),
            category: "trait",
            title: "MC1R D294H (Red Hair)",
            summary: "Strong red hair variant. The C allele is one of the high-penetrance MC1R red hair alleles.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.02),
        },
        Annotation {
            rsid: "rs1805008",
            gene: Some("MC1R"),
            category: "trait",
            title: "MC1R R160W (Red Hair)",
            summary: "Another red hair variant in the MC1R gene. The T allele reduces melanocortin-1 receptor function.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.09),
        },
        Annotation {
            rsid: "rs6318",
            gene: Some("HTR2C"),
            category: "trait",
            title: "Serotonin 2C Receptor Variant",
            summary: "Affects serotonin receptor function. The G allele is associated with altered appetite, mood regulation, and antipsychotic response.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "moderate",
            source: "snpedia",
            source_id: None,
            population_frequency: Some(0.13),
        },
        Annotation {
            rsid: "rs1800497",
            gene: Some("ANKK1"),
            category: "trait",
            title: "DRD2 Taq1A (Reward Processing)",
            summary: "The A1 allele (T) is associated with reduced striatal D2 receptor density, affecting reward sensitivity and learning from negative feedback.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "moderate",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.21),
        },
        Annotation {
            rsid: "rs1800588",
            gene: Some("LIPC"),
            category: "trait",
            title: "LIPC HDL Cholesterol Levels",
            summary: "Affects hepatic lipase activity. The T allele is associated with higher HDL cholesterol levels.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.21),
        },
        Annotation {
            rsid: "rs1815739",
            gene: Some("ACTN3"),
            category: "trait",
            title: "ACTN3 Athletic Performance",
            summary: "CC = power/sprint advantage, TT = endurance advantage. The most replicated sports genetics finding.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "strong",
            source: "gwas_catalog",
            source_id: None,
            population_frequency: Some(0.42),
        },
        Annotation {
            rsid: "rs4680",
            gene: Some("COMT"),
            category: "trait",
            title: "Pain Sensitivity (COMT)",
            summary: "The Met variant (A allele) is associated with higher pain sensitivity and lower pain tolerance in several studies.",
            risk_allele: None,
            normal_allele: None,
            significance: "benign",
            evidence_level: "moderate",
            source: "clinvar",
            source_id: Some("4680"),
            population_frequency: Some(0.49),
        },
        // ========================================================================
        // Carrier Status variants
        // ========================================================================
        Annotation {
            rsid: "rs77010898",
            gene: Some("CFTR"),
            category: "carrier_status",
            title: "Cystic Fibrosis Carrier (delta F508)",
            summary: "Most common cystic fibrosis mutation. Carriers (heterozygous) are unaffected but can pass the variant to children.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("7105"),
            population_frequency: Some(0.02),
        },
        Annotation {
            rsid: "rs80338939",
            gene: Some("SMN1"),
            category: "carrier_status",
            title: "Spinal Muscular Atrophy Carrier",
            summary: "Associated with spinal muscular atrophy carrier status. SMA is an autosomal recessive neuromuscular disorder.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("8022"),
            population_frequency: Some(0.02),
        },
        Annotation {
            rsid: "rs334",
            gene: Some("HBB"),
            category: "carrier_status",
            title: "Sickle Cell Carrier Status",
            summary: "The sickle cell variant. Heterozygous carriers have sickle cell trait with generally mild effects. Two copies cause sickle cell disease.",
            risk_allele: Some("T"),
            normal_allele: Some("AA"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("15127"),
            population_frequency: Some(0.05),
        },
        Annotation {
            rsid: "rs1800562",
            gene: Some("HFE"),
            category: "carrier_status",
            title: "Hemochromatosis Carrier (C282Y)",
            summary: "Heterozygous carriers of the C282Y HFE variant. Single copy usually does not cause clinical hemochromatosis.",
            risk_allele: Some("A"),
            normal_allele: Some("GG"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("5322"),
            population_frequency: Some(0.06),
        },
        Annotation {
            rsid: "rs1801131",
            gene: Some("MTHFR"),
            category: "carrier_status",
            title: "MTHFR A1298C Carrier",
            summary: "Carrier of the A1298C MTHFR variant. Single copy has minimal clinical impact on folate metabolism.",
            risk_allele: Some("C"),
            normal_allele: Some("AA"),
            significance: "likely_pathogenic",
            evidence_level: "moderate",
            source: "clinvar",
            source_id: Some("3522"),
            population_frequency: Some(0.30),
        },
        Annotation {
            rsid: "rs11970286",
            gene: Some("GJB2"),
            category: "carrier_status",
            title: "Connexin 26 Hearing Loss Carrier",
            summary: "Associated with autosomal recessive nonsyndromic hearing loss. Most common genetic cause of congenital deafness.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("17013"),
            population_frequency: Some(0.02),
        },
        Annotation {
            rsid: "rs76151636",
            gene: Some("HBB"),
            category: "carrier_status",
            title: "Beta-Thalassemia Carrier",
            summary: "Associated with beta-thalassemia trait. Carriers typically have mild microcytic anemia.",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("15130"),
            population_frequency: Some(0.01),
        },
        Annotation {
            rsid: "rs121908769",
            gene: Some("HEXA"),
            category: "carrier_status",
            title: "Tay-Sachs Carrier",
            summary: "Associated with Tay-Sachs disease carrier status. Common in Ashkenazi Jewish populations (~1 in 30 carrier frequency).",
            risk_allele: Some("T"),
            normal_allele: Some("CC"),
            significance: "pathogenic",
            evidence_level: "strong",
            source: "clinvar",
            source_id: Some("3944"),
            population_frequency: Some(0.003),
        },
    ]
}
