// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) OwnPulse Contributors

//! Parser for 23andMe raw data files.
//!
//! Format: tab-separated, 4 columns: rsid, chromosome, position, genotype.
//! Lines starting with `#` are comments.

use std::io::BufRead;

use super::parser::{ParseError, ParsedVariant, is_valid_chromosome, is_valid_genotype};

/// Parse a 23andMe file, yielding one `ParsedVariant` per valid data line.
pub fn parse(reader: impl BufRead) -> impl Iterator<Item = Result<ParsedVariant, ParseError>> {
    reader.lines().filter_map(|line_result| {
        match line_result {
            Err(e) => Some(Err(ParseError::Io(e))),
            Ok(line) => {
                let trimmed = line.trim();
                // Skip empty lines and comments
                if trimmed.is_empty() || trimmed.starts_with('#') {
                    return None;
                }
                Some(parse_line(trimmed))
            }
        }
    })
}

fn parse_line(line: &str) -> Result<ParsedVariant, ParseError> {
    let fields: Vec<&str> = line.split('\t').collect();
    if fields.len() != 4 {
        return Err(ParseError::InvalidLine(format!(
            "expected 4 tab-separated fields, got {}",
            fields.len()
        )));
    }

    let rsid = fields[0].trim();
    let chromosome = fields[1].trim();
    let position_str = fields[2].trim();
    let genotype = fields[3].trim();

    // rsid must start with "rs" or "i" (internal 23andMe IDs)
    if !rsid.starts_with("rs") && !rsid.starts_with('i') {
        return Err(ParseError::InvalidRsid(rsid.to_string()));
    }

    if !is_valid_chromosome(chromosome) {
        return Err(ParseError::InvalidChromosome(chromosome.to_string()));
    }

    let position: i64 = position_str
        .parse()
        .map_err(|_| ParseError::InvalidPosition(position_str.to_string()))?;

    if !is_valid_genotype(genotype) {
        return Err(ParseError::InvalidGenotype(genotype.to_string()));
    }

    Ok(ParsedVariant {
        rsid: rsid.to_string(),
        chromosome: chromosome.to_string(),
        position,
        genotype: genotype.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[test]
    fn parse_valid_file() {
        let input = "# This data file generated by 23andMe\n\
                     # rsid\tchromosome\tposition\tgenotype\n\
                     rs4477212\t1\t82154\tAA\n\
                     rs3094315\t1\t752566\tAG\n\
                     i713426\t1\t2345\tCC\n";

        let reader = Cursor::new(input);
        let results: Vec<_> = parse(reader).collect();

        assert_eq!(results.len(), 3);
        let v0 = results[0].as_ref().unwrap();
        assert_eq!(v0.rsid, "rs4477212");
        assert_eq!(v0.chromosome, "1");
        assert_eq!(v0.position, 82154);
        assert_eq!(v0.genotype, "AA");

        let v1 = results[1].as_ref().unwrap();
        assert_eq!(v1.rsid, "rs3094315");
        assert_eq!(v1.genotype, "AG");

        let v2 = results[2].as_ref().unwrap();
        assert_eq!(v2.rsid, "i713426");
    }

    #[test]
    fn skip_comment_lines() {
        let input = "# comment 1\n\
                     # comment 2\n\
                     # rsid\tchromosome\tposition\tgenotype\n\
                     rs1234\t1\t100\tAA\n";

        let reader = Cursor::new(input);
        let results: Vec<_> = parse(reader).collect();
        assert_eq!(results.len(), 1);
        assert!(results[0].is_ok());
    }

    #[test]
    fn invalid_line_too_few_fields() {
        let input = "rs1234\t1\t100\n";
        let reader = Cursor::new(input);
        let results: Vec<_> = parse(reader).collect();
        assert_eq!(results.len(), 1);
        assert!(results[0].is_err());
    }

    #[test]
    fn invalid_chromosome() {
        let input = "rs1234\t99\t100\tAA\n";
        let reader = Cursor::new(input);
        let results: Vec<_> = parse(reader).collect();
        assert!(results[0].is_err());
    }

    #[test]
    fn invalid_genotype() {
        let input = "rs1234\t1\t100\tXYZ\n";
        let reader = Cursor::new(input);
        let results: Vec<_> = parse(reader).collect();
        assert!(results[0].is_err());
    }
}
