// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) OwnPulse Contributors

//! MyChart / SMART-on-FHIR integration routes.
//!
//! Unlike the redirect-based Garmin/Oura flows, the MyChart connect flow is
//! driven by the client (iOS / web): the client performs the SMART launch and
//! the in-app authorization redirect, capturing the authorization `code`. It
//! then POSTs that code here together with the per-provider token endpoint and
//! FHIR base URL it discovered. The backend exchanges the code for tokens
//! (PKCE — no client secret), stores them encrypted, and persists the FHIR
//! connection metadata so the sync job can run later.

use axum::Json;
use axum::extract::State;
use chrono::Utc;
use serde::{Deserialize, Serialize};

use crate::AppState;
use crate::auth::extractor::AuthUser;
use crate::crypto;
use crate::db::integration_tokens;
use crate::error::ApiError;
use crate::integrations::mychart::{self, MyChartClient};
use crate::jobs::mychart_sync;

/// Request body for `POST /integrations/mychart/connect`.
#[derive(Deserialize)]
pub struct ConnectRequest {
    /// FHIR base URL (the SMART `iss`), e.g. `https://fhir.example.org/r4`.
    pub fhir_base_url: String,
    /// Provider token endpoint discovered from the SMART configuration.
    pub token_endpoint: String,
    /// Authorization code captured by the client redirect.
    pub code: String,
    /// Redirect URI used in the authorization request (must match exactly).
    pub redirect_uri: String,
    /// PKCE code verifier generated by the client.
    pub code_verifier: String,
}

#[derive(Serialize)]
pub struct ConnectResponse {
    pub source: String,
    pub connected: bool,
}

#[derive(Serialize)]
pub struct SyncResponse {
    pub source: String,
    pub imported: u32,
    pub skipped: u32,
}

/// POST /integrations/mychart/connect — exchange the SMART-on-FHIR
/// authorization code for tokens and store the connection.
pub async fn connect(
    State(state): State<AppState>,
    auth_user: AuthUser,
    Json(req): Json<ConnectRequest>,
) -> Result<Json<ConnectResponse>, ApiError> {
    let client_id = state
        .config
        .mychart_client_id
        .as_deref()
        .ok_or_else(|| ApiError::Internal("MYCHART_CLIENT_ID not configured".to_string()))?;

    // SSRF guard: the FHIR base URL and token endpoint are client-supplied and
    // the server connects to them directly. Reject non-HTTPS / internal hosts.
    let allow_insecure = state.config.mychart_allow_insecure_urls;
    mychart::validate_provider_url(&req.fhir_base_url, allow_insecure)
        .map_err(ApiError::BadRequest)?;
    mychart::validate_provider_url(&req.token_endpoint, allow_insecure)
        .map_err(ApiError::BadRequest)?;

    // Dedicated client: no redirects + resolved-address SSRF filter.
    let http = mychart::build_client(allow_insecure).map_err(ApiError::Internal)?;
    let client = MyChartClient::new(
        client_id.to_string(),
        req.token_endpoint.clone(),
        req.fhir_base_url.clone(),
        http,
    );

    let tokens = client
        .exchange_code(&req.code, &req.redirect_uri, &req.code_verifier)
        .await
        // Don't echo raw transport errors (may contain the resolved URL) to the
        // caller; log details server-side, return a generic message.
        .map_err(|e| {
            tracing::warn!(user_id = %auth_user.id, error = %e, "MyChart token exchange failed");
            ApiError::Internal("MyChart token exchange failed".to_string())
        })?;

    let encryption_key = crypto::parse_encryption_key(&state.config.encryption_key)?;

    let expires_at = tokens
        .expires_in
        .map(|secs| Utc::now() + chrono::Duration::seconds(secs));

    // Persist the non-secret FHIR connection parameters so the sync job can
    // reach the provider later. Tokens themselves are encrypted by `upsert`.
    let metadata = serde_json::json!({
        "fhir_base_url": req.fhir_base_url,
        "token_endpoint": req.token_endpoint,
    });

    integration_tokens::upsert_with_metadata(
        &state.pool,
        auth_user.id,
        mychart::SOURCE,
        &tokens.access_token,
        tokens.refresh_token.as_deref(),
        expires_at,
        Some(&metadata),
        &encryption_key,
    )
    .await
    .map_err(|e| ApiError::Internal(format!("failed to store MyChart tokens: {e}")))?;

    tracing::info!(user_id = %auth_user.id, "MyChart integration connected");

    Ok(Json(ConnectResponse {
        source: mychart::SOURCE.to_string(),
        connected: true,
    }))
}

/// POST /integrations/mychart/sync — fetch FHIR lab observations now and
/// import them into `lab_results`.
pub async fn sync(
    State(state): State<AppState>,
    auth_user: AuthUser,
) -> Result<Json<SyncResponse>, ApiError> {
    let outcome = mychart_sync::sync_user_now(&state.pool, &state.config, auth_user.id)
        .await
        // Generic message to the caller; transport details (which may include
        // the resolved provider URL) are logged server-side only.
        .map_err(|e| {
            tracing::warn!(user_id = %auth_user.id, error = %e, "MyChart sync failed");
            ApiError::Internal("MyChart sync failed".to_string())
        })?;

    if outcome.imported > 0 {
        let _ = state.event_tx.send((
            auth_user.id,
            crate::models::explore::DataChangedEvent {
                source: mychart::SOURCE.to_string(),
                record_type: Some("lab_result".to_string()),
            },
        ));
    }

    Ok(Json(SyncResponse {
        source: mychart::SOURCE.to_string(),
        imported: outcome.imported,
        skipped: outcome.skipped,
    }))
}
