// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) OwnPulse Contributors

//! Pact provider verification tests.
//!
//! Reads consumer contracts from `pact/contracts/*.json`, spins up the API
//! against a testcontainers Postgres, and replays every interaction to verify
//! the provider still satisfies them.

mod common;

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use bytes::Bytes;
use itertools::Either;
use pact_models::bodies::OptionalBody;
use pact_models::v4::http_parts::HttpRequest;
use pact_verifier::{
    callback_executors::{ProviderStateExecutor, RequestFilterExecutor},
    verify_provider_async, FilterInfo, PactSource, ProviderInfo, ProviderTransport,
    VerificationOptions,
};
use serde_json::Value;
use uuid::Uuid;

use common::ContractTestApp;

/// Shared token store between the state executor and request filter.
/// The state executor writes tokens here; the request filter reads them.
#[derive(Debug, Default)]
struct TokenStore {
    /// JWT for regular user interactions (`"Bearer some-jwt-token"`).
    user_token: Option<String>,
    /// JWT for admin interactions (`"Bearer some-admin-jwt-token"`).
    admin_token: Option<String>,
}

/// Request filter that replaces placeholder bearer tokens with real JWTs
/// generated by the state executor.
#[derive(Debug)]
struct JwtRequestFilter {
    tokens: Arc<Mutex<TokenStore>>,
}

impl RequestFilterExecutor for JwtRequestFilter {
    fn call(self: Arc<Self>, request: &HttpRequest) -> HttpRequest {
        let mut req = request.clone();
        let store = self.tokens.lock().expect("token store lock");

        if let Some(ref mut headers) = req.headers
            && let Some(auth) = headers.get_mut("Authorization")
        {
            let new_values: Vec<String> = auth
                .iter()
                .map(|val| {
                    if val == "Bearer some-jwt-token" {
                        store
                            .user_token
                            .as_ref()
                            .map(|t| format!("Bearer {t}"))
                            .unwrap_or_else(|| val.clone())
                    } else if val == "Bearer some-admin-jwt-token" {
                        store
                            .admin_token
                            .as_ref()
                            .map(|t| format!("Bearer {t}"))
                            .unwrap_or_else(|| val.clone())
                    } else {
                        val.clone()
                    }
                })
                .collect();
            *auth = new_values;
        }

        req
    }

    fn call_non_http(
        &self,
        request_body: &OptionalBody,
        metadata: &HashMap<String, Either<Value, Bytes>>,
    ) -> (OptionalBody, HashMap<String, Either<Value, Bytes>>) {
        (request_body.clone(), metadata.clone())
    }
}

/// Provider state callback that sets up the database state required by each
/// Pact interaction.
#[derive(Debug)]
struct StateExecutor {
    pool: sqlx::PgPool,
    jwt_secret: String,
    tokens: Arc<Mutex<TokenStore>>,
}

#[async_trait::async_trait]
impl ProviderStateExecutor for StateExecutor {
    async fn call(
        self: Arc<Self>,
        _interaction_id: Option<String>,
        provider_state: &pact_models::provider_states::ProviderState,
        _setup: bool,
        _client: Option<&reqwest::Client>,
    ) -> anyhow::Result<HashMap<String, Value>> {
        let state_name = &provider_state.name;
        let mut result = HashMap::new();

        match state_name.as_str() {
            "an authenticated user exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "an admin user exists" => {
                let (user_id, token) = create_admin_user(&self.pool, &self.jwt_secret).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                {
                    let mut store = self.tokens.lock().expect("token store lock");
                    store.admin_token = Some(token);
                }

                // Seed data so admin list endpoints return non-empty arrays.
                seed_admin_data(&self.pool).await;
            }
            _ => {
                tracing::warn!("unhandled provider state: {state_name}");
            }
        }

        Ok(result)
    }

    fn teardown(&self) -> bool {
        false
    }
}

async fn create_test_user(pool: &sqlx::PgPool, jwt_secret: &str) -> (Uuid, String) {
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");
    let row: (Uuid,) = sqlx::query_as(
        "INSERT INTO users (email, password_hash, auth_provider) \
         VALUES ($1, $2, 'local') RETURNING id",
    )
    .bind(format!("contract-user-{}@example.com", Uuid::new_v4()))
    .bind(&hash)
    .fetch_one(pool)
    .await
    .expect("insert test user");

    let token =
        api::auth::jwt::encode_access_token(row.0, "user", jwt_secret, 3600).expect("encode JWT");

    (row.0, token)
}

async fn create_admin_user(pool: &sqlx::PgPool, jwt_secret: &str) -> (Uuid, String) {
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");
    let uid = Uuid::new_v4();
    let row: (Uuid,) = sqlx::query_as(
        "INSERT INTO users (email, username, password_hash, auth_provider, role) \
         VALUES ($1, $2, $3, 'local', 'admin') RETURNING id",
    )
    .bind(format!("contract-admin-{}@example.com", uid))
    .bind(format!("admin-{}", &uid.to_string()[..8]))
    .bind(&hash)
    .fetch_one(pool)
    .await
    .expect("insert admin user");

    let token = api::auth::jwt::encode_access_token(row.0, "admin", jwt_secret, 3600)
        .expect("encode JWT");

    (row.0, token)
}

/// Seed data needed for admin list endpoints so they return non-empty arrays.
async fn seed_admin_data(pool: &sqlx::PgPool) {
    // Seed a second user so GET /admin/users returns at least one entry.
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");
    sqlx::query(
        "INSERT INTO users (email, username, password_hash, auth_provider, role) \
         VALUES ($1, $2, $3, 'google', 'user') \
         ON CONFLICT DO NOTHING",
    )
    .bind(format!("seeded-user-{}@example.com", Uuid::new_v4()))
    .bind(format!("seeded-{}", &Uuid::new_v4().to_string()[..8]))
    .bind(&hash)
    .execute(pool)
    .await
    .expect("seed user for admin list");

    // Seed an invite code so GET /admin/invites returns at least one entry.
    sqlx::query(
        "INSERT INTO invite_codes (code, label, max_uses, use_count, created_by) \
         SELECT $1, $2, $3, $4, id FROM users WHERE role = 'admin' LIMIT 1",
    )
    .bind(format!("SEED{}", &Uuid::new_v4().to_string()[..8]))
    .bind("Seeded invite")
    .bind(10_i32)
    .bind(0_i32)
    .execute(pool)
    .await
    .expect("seed invite code for admin list");
}

/// Resolve the path to `pact/contracts/` relative to the workspace root.
fn contracts_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../pact/contracts")
}

/// Verify a single contract file against the running provider.
async fn verify_contract(app: &ContractTestApp, contract_path: PathBuf) {
    let transport = ProviderTransport {
        transport: "HTTP".to_string(),
        port: Some(app.port),
        path: None,
        scheme: Some("http".to_string()),
    };

    let provider = ProviderInfo {
        name: "ownpulse-api".to_string(),
        host: "127.0.0.1".to_string(),
        transports: vec![transport],
        ..Default::default()
    };

    let source = PactSource::File(
        contract_path
            .to_str()
            .expect("contract path is valid UTF-8")
            .to_string(),
    );

    let tokens = Arc::new(Mutex::new(TokenStore::default()));

    let request_filter = Arc::new(JwtRequestFilter {
        tokens: tokens.clone(),
    });

    let options = VerificationOptions::<JwtRequestFilter> {
        disable_ssl_verification: true,
        request_filter: Some(request_filter),
        ..Default::default()
    };

    let state_executor = Arc::new(StateExecutor {
        pool: app.pool.clone(),
        jwt_secret: "test-jwt-secret-at-least-32-bytes-long".to_string(),
        tokens,
    });

    let result = verify_provider_async(
        provider,
        vec![source],
        FilterInfo::None,
        vec![],
        &options,
        None,
        &state_executor,
        None,
    )
    .await
    .expect("pact verification execution failed");

    assert!(
        result.result,
        "Pact verification failed for {}. Errors: {:?}",
        contract_path.display(),
        result.errors,
    );
}

#[tokio::test]
async fn verify_ios_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    if !contract.exists() {
        panic!("iOS contract file not found at {}", contract.display());
    }

    let app = common::setup().await;
    verify_contract(&app, contract).await;
}

#[tokio::test]
async fn verify_web_contract() {
    let contract = contracts_dir().join("web-backend.json");
    if !contract.exists() {
        panic!("Web contract file not found at {}", contract.display());
    }

    let app = common::setup().await;
    verify_contract(&app, contract).await;
}
