// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) OwnPulse Contributors

//! Pact provider verification tests.
//!
//! Reads consumer contracts from `pact/contracts/*.json`, spins up the API
//! against a testcontainers Postgres, and replays every interaction to verify
//! the provider still satisfies them.

mod common;

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use bytes::Bytes;
use itertools::Either;
use pact_models::bodies::OptionalBody;
use pact_models::v4::http_parts::HttpRequest;
#[allow(deprecated)]
use pact_verifier::{
    FilterInfo, PactSource, ProviderInfo, ProviderTransport, VerificationOptions,
    callback_executors::{ProviderStateExecutor, RequestFilterExecutor},
    verify_provider_async,
};
use serde_json::Value;
use uuid::Uuid;

use common::ContractTestApp;

/// Shared token store between the state executor and request filter.
/// The state executor writes tokens here; the request filter reads them.
#[derive(Debug, Default)]
struct TokenStore {
    /// JWT for regular user interactions (`"Bearer some-jwt-token"`).
    user_token: Option<String>,
    /// JWT for admin interactions (`"Bearer some-admin-jwt-token"`).
    admin_token: Option<String>,
}

/// Request filter that replaces placeholder bearer tokens with real JWTs
/// generated by the state executor.
#[derive(Debug)]
struct JwtRequestFilter {
    tokens: Arc<Mutex<TokenStore>>,
}

impl RequestFilterExecutor for JwtRequestFilter {
    fn call(self: Arc<Self>, request: &HttpRequest) -> HttpRequest {
        let mut req = request.clone();
        let store = self.tokens.lock().expect("token store lock");

        if let Some(ref mut headers) = req.headers
            && let Some(auth) = headers.get_mut("Authorization")
        {
            let new_values: Vec<String> = auth
                .iter()
                .map(|val| {
                    if val == "Bearer some-jwt-token" {
                        store
                            .user_token
                            .as_ref()
                            .map(|t| format!("Bearer {t}"))
                            .unwrap_or_else(|| val.clone())
                    } else if val == "Bearer some-admin-jwt-token" {
                        store
                            .admin_token
                            .as_ref()
                            .map(|t| format!("Bearer {t}"))
                            .unwrap_or_else(|| val.clone())
                    } else {
                        val.clone()
                    }
                })
                .collect();
            *auth = new_values;
        }

        req
    }

    fn call_non_http(
        &self,
        request_body: &OptionalBody,
        metadata: &HashMap<String, Either<Value, Bytes>>,
    ) -> (OptionalBody, HashMap<String, Either<Value, Bytes>>) {
        (request_body.clone(), metadata.clone())
    }
}

/// Provider state callback that sets up the database state required by each
/// Pact interaction.
#[derive(Debug)]
struct StateExecutor {
    pool: sqlx::PgPool,
    jwt_secret: String,
    tokens: Arc<Mutex<TokenStore>>,
}

#[async_trait::async_trait]
impl ProviderStateExecutor for StateExecutor {
    async fn call(
        self: Arc<Self>,
        _interaction_id: Option<String>,
        provider_state: &pact_models::provider_states::ProviderState,
        _setup: bool,
        _client: Option<&reqwest::Client>,
    ) -> anyhow::Result<HashMap<String, Value>> {
        // Skip teardown calls — we don't need to undo state between interactions.
        if !_setup {
            return Ok(HashMap::new());
        }

        let state_name = &provider_state.name;
        let mut result = HashMap::new();

        match state_name.as_str() {
            "an authenticated user exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "an admin user exists" => {
                let (user_id, token) = create_admin_user(&self.pool, &self.jwt_secret).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                {
                    let mut store = self.tokens.lock().expect("token store lock");
                    store.admin_token = Some(token);
                }

                // Seed data so admin list endpoints return non-empty arrays.
                seed_admin_data(&self.pool).await;
            }
            "a user with auth methods exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "a protocol with a loggable dose exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_dose_protocol(
                    &self.pool,
                    user_id,
                    "11111111-1111-1111-1111-111111111111",
                    "22222222-2222-2222-2222-222222222222",
                )
                .await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "a protocol with a skippable dose exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_dose_protocol(
                    &self.pool,
                    user_id,
                    "55555555-5555-5555-5555-555555555555",
                    "66666666-6666-6666-6666-666666666666",
                )
                .await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "a pending healthkit write-queue item exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_healthkit_write_queue_item(&self.pool, user_id).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "a protocol run with adherence data exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_adherence_run(
                    &self.pool,
                    user_id,
                    "aaaaaaaa-1111-1111-1111-111111111111",
                    "aaaaaaaa-2222-2222-2222-222222222222",
                    "aaaaaaaa-3333-3333-3333-333333333333",
                )
                .await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "a protocol run with a logged dose exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_logged_dose(&self.pool, user_id).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "an active protocol run with substances exists" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_active_substances_run(&self.pool, user_id).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "sleep records exist" => {
                let (user_id, token) = create_test_user(&self.pool, &self.jwt_secret).await;
                seed_sleep_record(&self.pool, user_id).await;
                result.insert("user_id".to_string(), Value::String(user_id.to_string()));
                result.insert("token".to_string(), Value::String(token.clone()));

                let mut store = self.tokens.lock().expect("token store lock");
                store.user_token = Some(token);
            }
            "the server is running" => {
                // No setup needed — the server is already running.
            }
            _ => {
                tracing::warn!("unhandled provider state: {state_name}");
            }
        }

        Ok(result)
    }

    fn teardown(&self) -> bool {
        false
    }
}

async fn create_test_user(pool: &sqlx::PgPool, jwt_secret: &str) -> (Uuid, String) {
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");
    let row: (Uuid,) = sqlx::query_as(
        "INSERT INTO users (email, password_hash, auth_provider) \
         VALUES ($1, $2, 'local') RETURNING id",
    )
    .bind(format!("contract-user-{}@example.com", Uuid::new_v4()))
    .bind(&hash)
    .fetch_one(pool)
    .await
    .expect("insert test user");

    let token = api::auth::jwt::encode_access_token(
        row.0,
        "user",
        jwt_secret,
        "http://localhost:5173",
        3600,
    )
    .expect("encode JWT");

    (row.0, token)
}

async fn create_admin_user(pool: &sqlx::PgPool, jwt_secret: &str) -> (Uuid, String) {
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");
    // Fixed UUID matching the iOS contract's expected admin user in list response.
    let admin_id: Uuid = "550e8400-e29b-41d4-a716-446655440000"
        .parse()
        .expect("valid UUID");

    let row: (Uuid,) = sqlx::query_as(
        "INSERT INTO users (id, email, username, password_hash, auth_provider, role) \
         VALUES ($1, $2, $3, $4, 'local', 'admin') \
         ON CONFLICT (id) DO UPDATE SET role = 'admin' \
         RETURNING id",
    )
    .bind(admin_id)
    .bind("admin@example.com")
    .bind("admin")
    .bind(&hash)
    .fetch_one(pool)
    .await
    .expect("insert admin user");

    let token = api::auth::jwt::encode_access_token(
        row.0,
        "admin",
        jwt_secret,
        "http://localhost:5173",
        3600,
    )
    .expect("encode JWT");

    (row.0, token)
}

/// Create the target user and invite code referenced by hardcoded UUIDs in iOS
/// contract request paths.
async fn seed_admin_data(pool: &sqlx::PgPool) {
    let target_user_id: Uuid = "550e8400-e29b-41d4-a716-446655440001"
        .parse()
        .expect("valid UUID");
    let hash = bcrypt::hash("testpassword", 4).expect("bcrypt hash");

    // Target user for PATCH …/role, PATCH …/status, DELETE …/users/:id
    // Status is 'disabled' because DELETE now requires the user to be disabled first.
    sqlx::query(
        "INSERT INTO users (id, email, username, password_hash, auth_provider, role, status) \
         VALUES ($1, $2, $3, $4, 'google', 'user', 'disabled') \
         ON CONFLICT (id) DO NOTHING",
    )
    .bind(target_user_id)
    .bind("testuser@example.com")
    .bind("testuser")
    .bind(&hash)
    .execute(pool)
    .await
    .expect("insert target user for admin interactions");

    // Invite code for DELETE /admin/invites/660e8400-…-440000 (only if table exists).
    let table_exists: (bool,) = sqlx::query_as(
        "SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_name = 'invite_codes'
        )",
    )
    .fetch_one(pool)
    .await
    .expect("check invite_codes table");

    if table_exists.0 {
        let admin_id: Uuid = "550e8400-e29b-41d4-a716-446655440000"
            .parse()
            .expect("valid UUID");
        let invite_id: Uuid = "660e8400-e29b-41d4-a716-446655440000"
            .parse()
            .expect("valid UUID");
        sqlx::query(
            "INSERT INTO invite_codes (id, code, label, max_uses, use_count, created_by) \
             VALUES ($1, 'ABC123DEF456', 'Friends', 10, 3, $2) \
             ON CONFLICT (id) DO NOTHING",
        )
        .bind(invite_id)
        .bind(admin_id)
        .execute(pool)
        .await
        .expect("insert invite code for admin interactions");
    }
}

/// Seed a protocol + protocol line (with fixed ids) for the ios-backend
/// contract's dose log/skip interactions, which reference these ids directly
/// in their request paths and bodies. `schedule_pattern` covers both day 0
/// (log interaction) and day 1 (skip interaction) so the same helper can seed
/// either fixture.
async fn seed_dose_protocol(pool: &sqlx::PgPool, user_id: Uuid, protocol_id: &str, line_id: &str) {
    let protocol_id: Uuid = protocol_id.parse().expect("valid protocol UUID");
    let line_id: Uuid = line_id.parse().expect("valid protocol_line UUID");

    sqlx::query(
        "INSERT INTO protocols (id, user_id, name, start_date, duration_days) \
         VALUES ($1, $2, 'Contract Test Protocol', CURRENT_DATE, 7)",
    )
    .bind(protocol_id)
    .bind(user_id)
    .execute(pool)
    .await
    .expect("seed contract-test protocol");

    sqlx::query(
        "INSERT INTO protocol_lines \
            (id, protocol_id, substance, dose, unit, route, schedule_pattern) \
         VALUES ($1, $2, 'Creatine', 5.0, 'g', 'oral', \
                 '[true, true, true, true, true, true, true]'::jsonb)",
    )
    .bind(line_id)
    .bind(protocol_id)
    .execute(pool)
    .await
    .expect("seed contract-test protocol line");
}

/// Seed a HealthKit write-queue row with the fixed id the ios-backend
/// contract references directly (`77777777-…`), so both the write-queue-list
/// and confirm-with-failures interactions can pin the same real item. Reruns
/// `DELETE` first because the `write-queue` and `confirm` interactions each
/// invoke this provider state independently, creating a *new* test user per
/// interaction — rebinding the fixed id to whichever user is running keeps
/// the row owned by the request that's about to read/mutate it.
async fn seed_healthkit_write_queue_item(pool: &sqlx::PgPool, user_id: Uuid) {
    let queue_id: Uuid = "77777777-7777-7777-7777-777777777777"
        .parse()
        .expect("valid UUID");
    let value = serde_json::json!({
        "value": 82.5,
        "unit": "kg",
        // date-ok
        "start_time": "2026-03-20T10:00:00Z",
        // date-ok
        "end_time": "2026-03-20T10:00:00Z",
    });

    sqlx::query("DELETE FROM healthkit_write_queue WHERE id = $1")
        .bind(queue_id)
        .execute(pool)
        .await
        .expect("clear existing contract-test write-queue row");

    sqlx::query(
        "INSERT INTO healthkit_write_queue (id, user_id, hk_type, value) \
         VALUES ($1, $2, 'body_mass', $3)",
    )
    .bind(queue_id)
    .bind(user_id)
    .bind(&value)
    .execute(pool)
    .await
    .expect("seed contract-test write-queue item");
}

/// Seed a protocol + line + active run (with fixed ids) for the ios-backend
/// contract's adherence/missed-doses interactions. `start_date` is set to
/// three days before `CURRENT_DATE`; combined with a daily (all-true)
/// 7-day pattern and no doses logged, this gives a deterministic result
/// regardless of when the test runs: `today_day == 3`, so the closed days
/// are 0/1/2 (day 3, today, is not yet closed — see `dose_status::
/// closed_bound`), all scheduled and missed, giving `scheduled_so_far=3,
/// completed=0, skipped=0, missed=3, adherence_pct=0.0`. Every field here is
/// deterministic and exact-matched; only `/missed-doses`' `date` field
/// (which depends on the real calendar date) needs a Pact type matcher.
async fn seed_adherence_run(
    pool: &sqlx::PgPool,
    user_id: Uuid,
    protocol_id: &str,
    line_id: &str,
    run_id: &str,
) {
    let protocol_id: Uuid = protocol_id.parse().expect("valid protocol UUID");
    let line_id: Uuid = line_id.parse().expect("valid protocol_line UUID");
    let run_id: Uuid = run_id.parse().expect("valid protocol_run UUID");

    // This provider state backs two interactions ("get run adherence" and
    // "list missed doses"), each re-running the full state setup with the
    // same fixed protocol/line/run ids but a freshly-created (different)
    // user per call. `ON CONFLICT DO UPDATE` re-parents the fixed rows to
    // whichever user this call created, so the run's ownership always
    // matches the token used for that interaction's request.
    sqlx::query(
        "INSERT INTO protocols (id, user_id, name, duration_days) \
         VALUES ($1, $2, 'Contract Adherence Protocol', 7) \
         ON CONFLICT (id) DO UPDATE SET user_id = excluded.user_id",
    )
    .bind(protocol_id)
    .bind(user_id)
    .execute(pool)
    .await
    .expect("seed contract-test adherence protocol");

    sqlx::query(
        "INSERT INTO protocol_lines \
            (id, protocol_id, substance, dose, unit, route, schedule_pattern) \
         VALUES ($1, $2, 'Creatine', 5.0, 'g', 'oral', \
                 '[true, true, true, true, true, true, true]'::jsonb) \
         ON CONFLICT (id) DO NOTHING",
    )
    .bind(line_id)
    .bind(protocol_id)
    .execute(pool)
    .await
    .expect("seed contract-test adherence line");

    sqlx::query(
        "INSERT INTO protocol_runs (id, protocol_id, user_id, start_date, status) \
         VALUES ($1, $2, $3, CURRENT_DATE - 3, 'active') \
         ON CONFLICT (id) DO UPDATE SET user_id = excluded.user_id",
    )
    .bind(run_id)
    .bind(protocol_id)
    .bind(user_id)
    .execute(pool)
    .await
    .expect("seed contract-test adherence run");
}

/// Seed a protocol + line + active run (reusing `seed_adherence_run`'s fixed
/// ids — the iOS undo-dose fixture's request path targets the same run,
/// `aaaaaaaa-3333-…`, and the dose-status fixture returned alongside it in
/// the same iOS PR references the same line, `aaaaaaaa-2222-…`) plus one
/// logged `protocol_doses` row at a fixed id, for the ios-backend contract's
/// "undo a logged dose" interaction.
async fn seed_logged_dose(pool: &sqlx::PgPool, user_id: Uuid) {
    seed_adherence_run(
        pool,
        user_id,
        "aaaaaaaa-1111-1111-1111-111111111111",
        "aaaaaaaa-2222-2222-2222-222222222222",
        "aaaaaaaa-3333-3333-3333-333333333333",
    )
    .await;

    let dose_id: Uuid = "bbbbbbbb-4444-4444-4444-444444444444"
        .parse()
        .expect("valid UUID");
    let line_id: Uuid = "aaaaaaaa-2222-2222-2222-222222222222"
        .parse()
        .expect("valid UUID");
    let run_id: Uuid = "aaaaaaaa-3333-3333-3333-333333333333"
        .parse()
        .expect("valid UUID");

    // This provider state's fixed dose id is only reachable from this one
    // call in any given test run, but re-run `DELETE`-then-`INSERT` anyway,
    // matching `seed_healthkit_write_queue_item`'s idempotency pattern —
    // cheap insurance against the `UNIQUE (protocol_line_id, run_id,
    // day_number)` constraint if this state is ever invoked more than once.
    sqlx::query("DELETE FROM protocol_doses WHERE id = $1")
        .bind(dose_id)
        .execute(pool)
        .await
        .expect("clear existing contract-test dose row");

    sqlx::query(
        "INSERT INTO protocol_doses (id, protocol_line_id, run_id, day_number, status, logged_at) \
         VALUES ($1, $2, $3, 0, 'completed', now())",
    )
    .bind(dose_id)
    .bind(line_id)
    .bind(run_id)
    .execute(pool)
    .await
    .expect("seed contract-test logged dose");
}

/// Seed a protocol ("Recovery Stack") + line (BPC-157, 250 mcg,
/// subcutaneous) + active run for the ios-backend contract's "list active
/// protocol substances for quick-pick" interaction. `active_substances` is
/// scoped to the caller's own active runs (see `db::active_substances`), so
/// a dedicated user per call — same as every other seeder here — keeps the
/// exact-match response body to exactly the one row the contract expects.
async fn seed_active_substances_run(pool: &sqlx::PgPool, user_id: Uuid) {
    let protocol_id: Uuid = "cccccccc-1111-1111-1111-111111111111"
        .parse()
        .expect("valid UUID");
    let line_id: Uuid = "cccccccc-2222-2222-2222-222222222222"
        .parse()
        .expect("valid UUID");
    let run_id: Uuid = "cccccccc-3333-3333-3333-333333333333"
        .parse()
        .expect("valid UUID");

    sqlx::query(
        "INSERT INTO protocols (id, user_id, name, duration_days) \
         VALUES ($1, $2, 'Recovery Stack', 30) \
         ON CONFLICT (id) DO UPDATE SET user_id = excluded.user_id",
    )
    .bind(protocol_id)
    .bind(user_id)
    .execute(pool)
    .await
    .expect("seed contract-test active-substances protocol");

    sqlx::query(
        "INSERT INTO protocol_lines \
            (id, protocol_id, substance, dose, unit, route, schedule_pattern) \
         VALUES ($1, $2, 'BPC-157', 250.0, 'mcg', 'subcutaneous', \
                 '[true, true, true, true, true, true, true]'::jsonb) \
         ON CONFLICT (id) DO NOTHING",
    )
    .bind(line_id)
    .bind(protocol_id)
    .execute(pool)
    .await
    .expect("seed contract-test active-substances line");

    sqlx::query(
        "INSERT INTO protocol_runs (id, protocol_id, user_id, start_date, status) \
         VALUES ($1, $2, $3, CURRENT_DATE, 'active') \
         ON CONFLICT (id) DO UPDATE SET user_id = excluded.user_id",
    )
    .bind(run_id)
    .bind(protocol_id)
    .bind(user_id)
    .execute(pool)
    .await
    .expect("seed contract-test active-substances run");
}

/// Seed a sleep observation so the web contract's `GET /api/v1/sleep` returns
/// a non-empty array.  Sleep records are stored in the `observations` table
/// with `type = 'sleep'`.
async fn seed_sleep_record(pool: &sqlx::PgPool, user_id: Uuid) {
    let value = serde_json::json!({
        "duration_minutes": 480,
        "deep_minutes": 90,
        "light_minutes": 210,
        "rem_minutes": 120,
        "awake_minutes": 60,
        "score": 82,
        // date-ok
        "date": "2026-03-10",
    });

    sqlx::query(
        // date-ok
        "INSERT INTO observations (user_id, type, name, start_time, end_time, value, source) \
         VALUES ($1, 'sleep', 'sleep', '2026-03-09T23:00:00Z', '2026-03-10T07:00:00Z', $2, 'manual')",
    )
    .bind(user_id)
    .bind(&value)
    .execute(pool)
    .await
    .expect("seed sleep observation");
}

/// Resolve the path to `pact/contracts/` relative to the workspace root.
fn contracts_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../pact/contracts")
}

/// Verify a single contract file against the running provider.
///
/// `filter` restricts which interactions are replayed. Pass [`FilterInfo::None`]
/// to verify the whole contract, or [`FilterInfo::Description`] (whose argument is
/// a regex over the interaction description) to verify a subset.
///
/// `expected_verified`, when `Some(n)`, asserts that exactly `n` interactions were
/// actually replayed. This guards against the silent failure mode where a
/// description filter matches zero interactions: `verify_provider_async` reports
/// success when nothing ran, so without this check a renamed interaction would
/// make the gate pass while verifying nothing.
async fn verify_contract(
    app: &ContractTestApp,
    contract_path: PathBuf,
    filter: FilterInfo,
    expected_verified: Option<usize>,
) {
    let transport = ProviderTransport {
        transport: "HTTP".to_string(),
        port: Some(app.port),
        path: None,
        scheme: Some("http".to_string()),
    };

    #[allow(deprecated)]
    let provider = ProviderInfo {
        name: "ownpulse-api".to_string(),
        host: "127.0.0.1".to_string(),
        port: Some(app.port),
        transports: vec![transport],
        ..Default::default()
    };

    let source = PactSource::File(
        contract_path
            .to_str()
            .expect("contract path is valid UTF-8")
            .to_string(),
    );

    let tokens = Arc::new(Mutex::new(TokenStore::default()));

    let request_filter = Arc::new(JwtRequestFilter {
        tokens: tokens.clone(),
    });

    let options = VerificationOptions::<JwtRequestFilter> {
        disable_ssl_verification: true,
        request_filter: Some(request_filter),
        ..Default::default()
    };

    let state_executor = Arc::new(StateExecutor {
        pool: app.pool.clone(),
        jwt_secret: "test-jwt-secret-at-least-32-bytes-long".to_string(),
        tokens,
    });

    let result = verify_provider_async(
        provider,
        vec![source],
        filter,
        vec![],
        &options,
        None,
        &state_executor,
        None,
    )
    .await
    .expect("pact verification execution failed");

    assert!(
        result.result,
        "Pact verification failed for {}. Errors: {:?}",
        contract_path.display(),
        result.errors,
    );

    if let Some(expected) = expected_verified {
        let verified = result.interaction_results.len();
        assert_eq!(
            verified,
            expected,
            "expected {expected} interaction(s) to be verified for {}, but {verified} ran — \
             did the contract's interaction descriptions change so the filter no longer matches? \
             Verified: {:?}",
            contract_path.display(),
            result
                .interaction_results
                .iter()
                .map(|r| r.description.as_str())
                .collect::<Vec<_>>(),
        );
    }
}

/// Regex matching the iOS HealthKit-sync interactions in `ios-backend.json`.
///
/// The sync and confirm interactions are fully deterministic (fixed status
/// codes and bodies, e.g. `{"received":1,"inserted":1,...}` and an empty 204).
/// The write-queue interaction seeds one real pending item at a fixed id
/// (`seed_healthkit_write_queue_item`) and uses `type` matchers for the two
/// fields the provider necessarily generates dynamically (`user_id`,
/// `scheduled_at`) — everything else, including the full `value` JSONB shape,
/// is matched by exact equality. Together these form the active, CI-enforced
/// slice of the iOS Pact gate: if a change to `/healthkit/sync`,
/// `/healthkit/write-queue`, or `/healthkit/confirm` alters the status code or
/// response shape away from what iOS expects, this test fails.
const IOS_HEALTHKIT_INTERACTIONS: &str = "^a request to (bulk sync HealthKit records|\
get the HealthKit write-back queue|confirm HealthKit write-back items)$";

/// The active iOS Pact gate.
///
/// This is NOT `#[ignore]`d — it runs on `cargo test --test contract` and in CI,
/// and it FAILS if the provider drifts from the iOS HealthKit-sync contract.
///
/// It deliberately verifies only the deterministic HealthKit-sync subset (see
/// [`IOS_HEALTHKIT_INTERACTIONS`]). Most of the remaining iOS interactions
/// cannot be verified today because the committed `ios-backend.json` is a
/// Pact v2 document with no matching rules for them: every dynamic field
/// (generated UUIDs, timestamps, invite codes) and every literal path id
/// (`proto-1`, fixed admin UUIDs) is matched by exact equality, which a real
/// provider can never satisfy. The protocol dose log/skip interactions are
/// the one exception — see [`verify_ios_dose_contract`], which does add
/// matching rules and seeded state for just those two. Bringing the rest of
/// the contract under verification requires the same treatment for every
/// other interaction — tracked by `verify_ios_contract` below, which stays
/// `#[ignore]`d until that work lands.
#[tokio::test]
async fn verify_ios_healthkit_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let app = common::setup().await;
    verify_contract(
        &app,
        contract,
        FilterInfo::Description(IOS_HEALTHKIT_INTERACTIONS.to_string()),
        // The three HealthKit-sync interactions must all run — see the doc on
        // `expected_verified`. A renamed interaction must fail the gate, not
        // silently skip it.
        Some(3),
    )
    .await;
}

/// Regex matching the iOS protocol dose log/skip interactions in
/// `ios-backend.json`. These interactions seed real provider state (see
/// `seed_dose_protocol`) with fixed UUIDs and use `type` matchers on the
/// server-generated `id`/`intervention_id`/`logged_at` response fields, so
/// they can be verified deterministically against the live provider.
const IOS_DOSE_INTERACTIONS: &str = "^a request to (log|skip) a protocol dose$";

/// Active iOS Pact gate for the protocol dose log/skip endpoints.
///
/// Regression test for the `line_id` / `protocol_line_id` field-name mismatch
/// between the backend and clients: the backend request/response structs
/// used to use `line_id` while the contract (and both clients) send/expect
/// `protocol_line_id`, silently breaking dose logging in production. This
/// test is NOT `#[ignore]`d — it fails the build if either interaction is
/// ever renamed out of `IOS_DOSE_INTERACTIONS` (silent-skip guard) or if the
/// provider's request/response shape drifts from the contract again.
#[tokio::test]
async fn verify_ios_dose_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let app = common::setup().await;
    verify_contract(
        &app,
        contract,
        FilterInfo::Description(IOS_DOSE_INTERACTIONS.to_string()),
        Some(2),
    )
    .await;
}

/// Regex matching the iOS adherence/missed-doses interactions in
/// `ios-backend.json`. These seed a deterministic protocol run (see
/// `seed_adherence_run`) via fixed UUIDs and a fixed `start_date` offset, so
/// they verify against the live provider with only a `type` matcher on the
/// calendar-date-dependent `date` fields.
const IOS_ADHERENCE_INTERACTIONS: &str = "^a request to (get run adherence|list missed doses)$";

/// Active iOS Pact gate for the run-adherence and missed-doses read
/// endpoints (`GET /protocols/runs/:run_id/adherence`,
/// `GET /protocols/runs/missed-doses`). Follows the same verified-slice
/// pattern as [`verify_ios_dose_contract`]: NOT `#[ignore]`d, fails if the
/// provider's response shape drifts from the contract or if either
/// interaction is renamed out of `IOS_ADHERENCE_INTERACTIONS`.
#[tokio::test]
async fn verify_ios_adherence_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let app = common::setup().await;
    verify_contract(
        &app,
        contract,
        FilterInfo::Description(IOS_ADHERENCE_INTERACTIONS.to_string()),
        Some(2),
    )
    .await;
}

/// Count interactions in `contract_path` whose `description` exactly equals
/// one of `descriptions`. Reads and parses the pact JSON directly, entirely
/// independent of the regex `FilterInfo` that `verify_contract` passes to
/// `pact_verifier` — the point is to give the not-yet-landed tests below a
/// genuine second source of truth for `expected_verified` rather than
/// re-deriving the same number from the same filter twice (which would
/// trivially agree with itself even if the filter regex were wrong).
fn interaction_count(contract_path: &std::path::Path, descriptions: &[&str]) -> usize {
    let raw = std::fs::read_to_string(contract_path).expect("read contract file");
    let json: Value = serde_json::from_str(&raw).expect("parse contract JSON");
    json["interactions"]
        .as_array()
        .expect("interactions is an array")
        .iter()
        .filter(|interaction| {
            interaction["description"]
                .as_str()
                .is_some_and(|d| descriptions.contains(&d))
        })
        .count()
}

/// Exact interaction descriptions added by `feat/ios-dose-backfill-adherence`
/// (PR #318, unmerged at the time this test was written) to
/// `ios-backend.json`. Backs [`verify_ios_dose_status_contract`].
const IOS_DOSE_STATUS_DESCRIPTIONS: &[&str] = &[
    "a request to get dose status for a run's scheduled days",
    "a request to undo a logged dose",
];

/// Regex matching the same two interactions, for `pact_verifier`'s
/// `FilterInfo::Description`.
const IOS_DOSE_STATUS_INTERACTIONS: &str =
    "^a request to (get dose status for a run's scheduled days|undo a logged dose)$";

/// Active iOS Pact gate for the run-doses (dose-status) and undo-dose
/// endpoints (`GET /protocols/runs/:run_id/doses`,
/// `DELETE /protocols/runs/:run_id/doses/:dose_id`).
///
/// These two interactions ship on `feat/ios-dose-backfill-adherence`
/// (PR #318) — that PR, not this one, owns the `ios-backend.json` change
/// that adds them. On `main` today, `ios-backend.json` doesn't contain them
/// yet, so instead of a hardcoded `expected_verified` (which would fail
/// before the interactions exist), `expected_verified` is computed by
/// [`interaction_count`] from whatever contract file is actually loaded:
/// `0` today (test passes vacuously — there is nothing to verify yet), `2`
/// once PR #318 merges and the interactions land, at which point this
/// becomes a real verification. The provider state it depends on,
/// "a protocol run with a logged dose exists" (`seed_logged_dose`), already
/// exists so that day-one verification works without a follow-up PR; "get
/// dose status for a run's scheduled days" reuses the existing "a protocol
/// run with adherence data exists" state (`seed_adherence_run`) unchanged.
#[tokio::test]
async fn verify_ios_dose_status_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let expected = interaction_count(&contract, IOS_DOSE_STATUS_DESCRIPTIONS);

    let app = common::setup().await;
    verify_contract(
        &app,
        contract,
        FilterInfo::Description(IOS_DOSE_STATUS_INTERACTIONS.to_string()),
        Some(expected),
    )
    .await;
}

/// Exact interaction description added by `feat/ios-quick-pick` (PR #319,
/// unmerged at the time this test was written) to `ios-backend.json`. Backs
/// [`verify_ios_quick_pick_contract`].
const IOS_QUICK_PICK_DESCRIPTIONS: &[&str] =
    &["a request to list active protocol substances for quick-pick"];

/// Regex matching the same interaction, for `pact_verifier`'s
/// `FilterInfo::Description`.
const IOS_QUICK_PICK_INTERACTIONS: &str =
    "^a request to list active protocol substances for quick-pick$";

/// Active iOS Pact gate for `GET /protocols/active-substances`.
///
/// Ships on `feat/ios-quick-pick` (PR #319) — see the doc comment on
/// [`verify_ios_dose_status_contract`] for why `expected_verified` is
/// computed via [`interaction_count`] rather than hardcoded: `0` on `main`
/// today, `1` once PR #319 merges. The provider state it depends on, "an
/// active protocol run with substances exists" (`seed_active_substances_run`),
/// already exists so verification is live from day one of the merge.
#[tokio::test]
async fn verify_ios_quick_pick_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let expected = interaction_count(&contract, IOS_QUICK_PICK_DESCRIPTIONS);

    let app = common::setup().await;
    verify_contract(
        &app,
        contract,
        FilterInfo::Description(IOS_QUICK_PICK_INTERACTIONS.to_string()),
        Some(expected),
    )
    .await;
}

/// Full iOS contract verification.
///
/// Ignored: `ios-backend.json` lacks Pact matching rules and seeded provider
/// state for most interactions (see [`verify_ios_healthkit_contract`]). Re-author
/// the contract with matchers and complete the `StateExecutor` seeding, then drop
/// this `#[ignore]`.
#[tokio::test]
#[ignore = "ios-backend.json needs matching rules + full provider-state seeding — tracked separately"]
async fn verify_ios_contract() {
    let contract = contracts_dir().join("ios-backend.json");
    assert!(
        contract.exists(),
        "iOS contract file not found at {}",
        contract.display()
    );

    let app = common::setup().await;
    verify_contract(&app, contract, FilterInfo::None, None).await;
}

/// Full web contract verification.
///
/// Ignored: `web-backend.json` provider states (e.g. "user is authenticated")
/// are not handled by the `StateExecutor`, and the contract lacks matching rules.
/// Re-author with matchers and complete provider-state seeding, then drop this
/// `#[ignore]`.
#[tokio::test]
#[ignore = "web-backend.json needs matching rules + full provider-state seeding — tracked separately"]
async fn verify_web_contract() {
    let contract = contracts_dir().join("web-backend.json");
    assert!(
        contract.exists(),
        "Web contract file not found at {}",
        contract.display()
    );

    let app = common::setup().await;
    verify_contract(&app, contract, FilterInfo::None, None).await;
}
