apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.componentName" (dict "component" "grafana" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "grafana" "context" $) | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "observability.selectorLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
