{{- if .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability.componentName" (dict "component" "grafana" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "grafana" "context" $) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
