apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability.componentName" (dict "component" "grafana" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "grafana" "context" $) | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.admin.user | b64enc | quote }}
  admin-password: {{ .Values.grafana.admin.password | b64enc | quote }}
