---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability.componentName" (dict "component" "grafana" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "grafana" "context" $) | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability.componentName" (dict "component" "loki" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "loki" "context" $) | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability.componentName" (dict "component" "tempo" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "tempo" "context" $) | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability.componentName" (dict "component" "alloy" "context" $) }}
  labels:
    {{- include "observability.labels" (dict "component" "alloy" "context" $) | nindent 4 }}
